#!/bin/sh -e

term_setup() {
    stty -icanon -echo

    printf '\033[?1049h\033[?7l\033[?25l\033[2J\033[1;%sr' \
        "$((LINES - 2))"
}

term_reset() {
    stty icanon echo

    printf '\033[?7h\033[?25h\e[2J\033[;r\033[?1049l'
}

term_resize() {
    set -f
    set +f -- $(stty size)

    LINES=$1 COLUMNS=$2

    # leave gap above statusline
    line_max=$((LINES - 2))
}

list_print() {
    printf '\033[2J\033[H'

    for file in *; do
        printf '%s\n' "$file"
    done
}

key_handle() {
    case $key$esc in
        k?|A2) # ARROW UP
        ;;

        j?|B2) # ARROW DOWN
        ;;

        l?|C2) # ARROW RIGHT
        ;;

        h?|D2) # ARROW LEFT
        ;;

        g?)
        ;;

        G?)
        ;;

        q?)
            exit 0
        ;;

        # handle keys which emit escape sequences
        ''*) esc=1 ;;
         '[1') esc=2 ;;
            *) esc=0 ;;
    esac
}

redraw() {
    list_print
    status_line
}

status_line() {
    printf '\0337\033[%sH\033[31;7m%-*s\033[m\0338' \
        "$LINES" "$COLUMNS" "${1:-$PWD}"
}

main() {
    # change directory to the first argument
    cd "${1:-"$PWD"}"

    term_resize
    term_setup
    redraw

    trap 'term_reset'  EXIT INT
    trap 'term_resize; redraw' WINCH

    while key=$(dd ibs=1 count=1 2>/dev/null); do
        key_handle "$key"
        redraw
    done
}

main "$@"
